__all__ = ["cancerGenomeInterpreterConfig",
            "drugbankConfig",
            "hmdbConfig",
            "oncokbConfig",
            "siderConfig",
            "disgenetConfig",
            "gwasCatalogConfig",
            "intactConfig",
            "pathwayCommonsConfig",
            "stringConfig",
            "drugGeneInteractionDBConfig",
            "hgncConfig",
            "internalDBsConfig",
            "refseqConfig",
            "uniprotConfig"]
