version=1.0
graphdb_builder_log="../../config/graphdb_builder_log.config"
graphdb_connector_log="../../config/graphdb_connector_log.config"
report_manager_log="../../config/report_manager_log.config"
connector_config_file="../../graphdb_connector/connector_config.yml"
builder_config_file="../../graphdb_builder/builder/builder_config.yml"
ontologies_config_file = "../../graphdb_builder/ontologies/ontologies_config.yml"
databases_config_file = "../../graphdb_builder/databases/databases_config.yml"
experiments_config_file = "../../graphdb_builder/experiments/experiments_config.yml"
